name: SFTP Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    - name: Print secret value
      run: echo ${{ secrets.PORTFOLIO_SITE_PASS }}
    - name: Deploy to SFTP server
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        server: sutherlin.dreamhost.com
        port: 22
        username: dh_z469ux
        password: ${{ secrets.PORTFOLIO_SITE_PASS }}
        local-dir: build/
        remote-dir: suhaybka.me
